WF_info ={}

WF_info['Clinical Variables - Complex Models'] = {'formal_title': 'Iodine Perfusion Prediction (Clinical Variables - Complex Models)',
				  'type': 'regression',
				  'label_name': 'Mean Iodine Density',
				  'label_time': None,
				  'feature_list': [	'Age',
									'AF History',
									'Sex (0: Woman, 1: Man)',
									'BMI',
									'Hypertension',
									'Diabetes',
									'Dyslipidaemia ',
									'Obesity',
									'Contrast Dose (mL)',
									'Blood Pool Iodine Density',
									'Myocardium Volume (mL)',
									'Smoking History',
									'Active Smoking',
									'Acquisition Type (0: Step-and-shoot, 1: Helical)',
									'Phase (0: Diastole, 1:Systole)'],
				  'filter_function': lambda df: df,
				  'group_label': None,
				  'validation_type':'kfold',
				  'cv_folds': 10,
				  'cv_repetitions': 10,
				  'external_validation': 'No',
				  'filter_external_validation': lambda df: df,
				  'models': ['BT', 'Linear', 'HypLasso', 'HypRidge'],
				  'metrics':['rmse','r2']}

WF_info['Clinical + Technical Variables - Complex Model'] = {'formal_title': 'Iodine Perfusion Prediction (Clinical + Technical Variables - Complex Model)',
				  'type': 'regression',
				  'label_name': 'Mean Iodine Density',
				  'label_time': None,
				  'feature_list': [	'Age',
									'AF History',
									'Sex (0: Woman, 1: Man)',
									'BMI',
									'Hypertension',
									'Diabetes',
									'Dyslipidaemia ',
									'Obesity',
									'Contrast Dose (mL)',
									'Blood Pool Iodine Density',
									'Myocardium Volume (mL)',
									'Smoking History',
									'Active Smoking',
									'Acquisition Type (0: Step-and-shoot, 1: Helical)',
									'Phase (0: Diastole, 1:Systole)',
									'Radiation Exposure, mA·s',
									'Radiation Exposure Time, ms',
									'X-Ray Current, mA',
									'Acquisition Duration',
									'CTDIvol',
									'Delay between tracker and acquisition'],
				  'filter_function': lambda df: df,
				  'group_label': None,
				  'validation_type':'kfold',
				  'cv_folds': 10,
				  'cv_repetitions': 10,
				  'external_validation': 'No',
				  'filter_external_validation': lambda df: df,
				  'models': ['BT', 'Linear', 'HypLasso', 'HypRidge'],
				  'metrics':['rmse','r2']}

WF_info['Clinical Variables - Simplified Models'] = {'formal_title': 'Iodine Perfusion Prediction (Clinical Variables - Simplified Models)',
				  'type': 'regression',
				  'label_name': 'Mean Iodine Density',
				  'label_time': None,
				  'feature_list': [	'Sex (0: Woman, 1: Man)',
									'BMI',
									'Myocardium Volume (mL)',
									'Acquisition Type (0: Step-and-shoot, 1: Helical)'],
				  'filter_function': lambda df: df,
				  'group_label': None,
				  'validation_type':'kfold',
				  'cv_folds': 10,
				  'cv_repetitions': 10,
				  'external_validation': 'No',
				  'filter_external_validation': lambda df: df,
				  'models': ['BT', 'Linear', 'HypLasso', 'HypRidge'],
				  'metrics':['rmse','r2']}

WF_info['Clinical + Technical Variables - Simplified Models'] = {'formal_title': 'Iodine Perfusion Prediction (Clinical + Technical Variables - Simplified Model)',
				  'type': 'regression',
				  'label_name': 'Mean Iodine Density',
				  'label_time': None,
				  'feature_list': [	'Sex (0: Woman, 1: Man)',
									'BMI',
									'Myocardium Volume (mL)',
									'X-Ray Current, mA',
									'Acquisition Duration',
									'Delay between tracker and acquisition'],
				  'filter_function': lambda df: df,
				  'group_label': None,
				  'validation_type':'kfold',
				  'cv_folds': 10,
				  'cv_repetitions': 10,
				  'external_validation': 'No',
				  'filter_external_validation': lambda df: df,
				  'models': ['BT', 'Linear', 'HypLasso', 'HypRidge'],
				  'metrics':['rmse','r2']}